# Generated by Django 4.1.2 on 2022-11-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='WorkerInfo',
        ),
    ]
