# Generated by Django 4.1.2 on 2022-12-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_drugs_manageinfo_workerinfo_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('worker_name', models.CharField(max_length=32)),
                ('drugs_name', models.CharField(max_length=32)),
                ('InOrOut', models.BooleanField()),
                ('num', models.IntegerField()),
            ],
        ),
    ]
