# Generated by Django 4.1.2 on 2023-01-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='god',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('time', models.DateTimeField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
