# Generated by Django 4.1.2 on 2023-01-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_god'),
    ]

    operations = [
        migrations.AlterField(
            model_name='god',
            name='phone',
            field=models.CharField(max_length=32),
        ),
    ]
