# Generated by Django 4.1.2 on 2023-02-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_delete_manage_manageinfo_system_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='god',
            name='drugs',
            field=models.CharField(default='999感冒灵', max_length=32),
        ),
    ]
